export interface GovtPortalItem {
  id: string;
  name: string;
  agency: string;
  category:
    | "central"
    | "railway"
    | "banking"
    | "defence"
    | "postal"
    | "teaching"
    | "psu"
    | "state_psc"
    | "employment";
  categoryLabel: string;
  url: string;
  stateOrRegion: string;
  description: string;
  tags: string[];
  popularExam?: string;
  featured?: boolean;
}

export const GOVT_PORTALS_DATA: GovtPortalItem[] = [
  // ==========================================
  // CENTRAL RECRUITMENT BOARDS (SSC, UPSC, NTA)
  // ==========================================
  {
    id: "portal-ssc",
    name: "Staff Selection Commission (SSC)",
    agency: "Ministry of Personnel, Public Grievances and Pensions",
    category: "central",
    categoryLabel: "Central SSC & UPSC",
    url: "https://ssc.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official portal for SSC CGL, CHSL, MTS, GD Constable, CPO SI, and Stenographer online applications.",
    tags: ["ssc", "cgl", "chsl", "mts", "gd constable", "cpo", "central govt jobs"],
    popularExam: "SSC CGL / CHSL / GD",
    featured: true,
  },
  {
    id: "portal-upsc",
    name: "Union Public Service Commission (UPSC)",
    agency: "UPSC Official Recruitment Portal",
    category: "central",
    categoryLabel: "Central SSC & UPSC",
    url: "https://upsc.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official portal for IAS, IPS, IFS, NDA, CDS, CAPF, Engineering Services, and Combined Medical Services.",
    tags: ["upsc", "ias", "ips", "nda", "cds", "capf", "civil services"],
    popularExam: "UPSC Civil Services / NDA / CDS",
    featured: true,
  },
  {
    id: "portal-upsc-online",
    name: "UPSC One-Time Registration (OTR) Portal",
    agency: "UPSC Online Application System",
    category: "central",
    categoryLabel: "Central SSC & UPSC",
    url: "https://upsconline.nic.in/",
    stateOrRegion: "All India (Central)",
    description: "Direct OTR profile creation and online application portal for all UPSC national recruitment exams.",
    tags: ["upsc otr", "upsc online", "apply upsc", "otr registration"],
    popularExam: "UPSC OTR Registration",
    featured: true,
  },
  {
    id: "portal-nta",
    name: "National Testing Agency (NTA)",
    agency: "Ministry of Education",
    category: "central",
    categoryLabel: "Central SSC & UPSC",
    url: "https://nta.ac.in/",
    stateOrRegion: "All India (Central)",
    description: "Official testing agency for UGC NET, CSIR NET, JEE, NEET, CUET, and central ministry recruitment tests.",
    tags: ["nta", "ugc net", "csir net", "cuet", "national testing agency"],
    popularExam: "UGC NET / CSIR NET / CUET",
    featured: false,
  },

  // ==========================================
  // RAILWAYS & TRANSPORT (RRB, RRC)
  // ==========================================
  {
    id: "portal-rrb-apply",
    name: "Railway Recruitment Board (RRB Apply Portal)",
    agency: "Ministry of Railways (Indian Railways)",
    category: "railway",
    categoryLabel: "Railway & Transport",
    url: "https://www.rrbapply.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Centralized application portal for RRB NTPC, Group D, ALP (Assistant Loco Pilot), Technician, and JE.",
    tags: ["rrb", "railway jobs", "rrb ntpc", "rrb group d", "rrb alp", "technician", "indian railways"],
    popularExam: "RRB NTPC / Group D / ALP",
    featured: true,
  },
  {
    id: "portal-indian-railways",
    name: "Indian Railways Official Recruitment Hub",
    agency: "Railway Board & All Regional RRBs",
    category: "railway",
    categoryLabel: "Railway & Transport",
    url: "https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,7,1281",
    stateOrRegion: "All India (Central)",
    description: "Directory for all 21 regional RRB boards (Kolkata, Mumbai, Patna, Chennai, Allahabad, Chandigarh, etc.).",
    tags: ["rrb regional", "rrb kolkata", "rrb patna", "rrc apprentice", "railway recruit"],
    popularExam: "All 21 Regional RRBs",
    featured: false,
  },

  // ==========================================
  // BANKING & FINANCIAL (IBPS, SBI, RBI, LIC)
  // ==========================================
  {
    id: "portal-ibps",
    name: "Institute of Banking Personnel Selection (IBPS)",
    agency: "IBPS Official Recruitment Portal",
    category: "banking",
    categoryLabel: "Banking & Finance",
    url: "https://www.ibps.in/",
    stateOrRegion: "All India (Central)",
    description: "Official portal for IBPS PO, IBPS Clerk, IBPS SO, and IBPS RRB Gramin Bank recruitment exams.",
    tags: ["ibps", "ibps po", "ibps clerk", "ibps rrb", "bank jobs", "bank po"],
    popularExam: "IBPS PO / Clerk / RRB",
    featured: true,
  },
  {
    id: "portal-sbi-careers",
    name: "State Bank of India (SBI Careers)",
    agency: "State Bank of India Corporate Centre",
    category: "banking",
    categoryLabel: "Banking & Finance",
    url: "https://bank.sbi/web/careers",
    stateOrRegion: "All India (Central)",
    description: "Official SBI recruitment portal for SBI PO, SBI Junior Associate (Clerk), SBI CBO, and Specialist Officers.",
    tags: ["sbi", "sbi po", "sbi clerk", "sbi careers", "sbi ja", "bank job"],
    popularExam: "SBI PO / SBI Clerk",
    featured: true,
  },
  {
    id: "portal-rbi-careers",
    name: "Reserve Bank of India (RBI Opportunities)",
    agency: "Reserve Bank of India Services Board",
    category: "banking",
    categoryLabel: "Banking & Finance",
    url: "https://opportunities.rbi.org.in/",
    stateOrRegion: "All India (Central)",
    description: "Official career page for RBI Grade B Officers, RBI Assistant, and RBI Specialist roles.",
    tags: ["rbi", "rbi grade b", "rbi assistant", "rbi recruitment", "central bank"],
    popularExam: "RBI Grade B / RBI Assistant",
    featured: true,
  },
  {
    id: "portal-lic-careers",
    name: "Life Insurance Corporation (LIC Careers)",
    agency: "Life Insurance Corporation of India",
    category: "banking",
    categoryLabel: "Banking & Finance",
    url: "https://licindia.in/Bottom-Navigation/Careers",
    stateOrRegion: "All India (Central)",
    description: "Official careers page for LIC ADO, LIC AAO, LIC Assistant, and HFL recruitment notifications.",
    tags: ["lic", "lic aao", "lic ado", "lic assistant", "insurance jobs"],
    popularExam: "LIC AAO / ADO / Assistant",
    featured: false,
  },

  // ==========================================
  // DEFENCE & POLICE (ARMY, NAVY, AIRFORCE, CAPF)
  // ==========================================
  {
    id: "portal-join-army",
    name: "Join Indian Army (Official Web Portal)",
    agency: "Directorate General of Recruiting, Indian Army",
    category: "defence",
    categoryLabel: "Police & Defence",
    url: "https://joinindianarmy.nic.in/",
    stateOrRegion: "All India (Central)",
    description: "Official portal for Agnipath Agniveer Army recruitment rally, Officer entry (TGC, SSC Tech, NCC), and Territorial Army.",
    tags: ["indian army", "agniveer army", "join indian army", "army rally", "defence jobs"],
    popularExam: "Agniveer Army / Officer Entries",
    featured: true,
  },
  {
    id: "portal-join-navy",
    name: "Join Indian Navy (Official Portal)",
    agency: "Integrated HQ of Ministry of Defence (Navy)",
    category: "defence",
    categoryLabel: "Police & Defence",
    url: "https://www.joinindiannavy.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official recruitment portal for Navy Agniveer SSR, Agniveer MR, Tradesman Mate, and Officer Entry.",
    tags: ["indian navy", "agniveer navy", "navy ssr", "navy mr", "tradesman mate"],
    popularExam: "Agniveer Navy SSR / MR",
    featured: true,
  },
  {
    id: "portal-afcat-airforce",
    name: "Indian Air Force AFCAT & Agniveer Vayu Portal",
    agency: "CDAC & Indian Air Force",
    category: "defence",
    categoryLabel: "Police & Defence",
    url: "https://afcat.cdac.in/AFCAT/",
    stateOrRegion: "All India (Central)",
    description: "Official portal for AFCAT Officer entry and Agniveer Vayu intake registration.",
    tags: ["iaf", "afcat", "agniveer vayu", "air force jobs", "iaf officer"],
    popularExam: "AFCAT / Agniveer Vayu",
    featured: true,
  },
  {
    id: "portal-crpf",
    name: "Central Reserve Police Force (CRPF Recruitment)",
    agency: "Ministry of Home Affairs",
    category: "defence",
    categoryLabel: "Police & Defence",
    url: "https://rect.crpf.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official CRPF portal for Constable Tradesman, Sub-Inspector (SI), Head Constable Ministerial, and Paramedical recruitment.",
    tags: ["crpf", "crpf constable", "crpf recruitment", "paramilitary", "crpf hcm"],
    popularExam: "CRPF Constable & Tradesman",
    featured: false,
  },
  {
    id: "portal-bsf",
    name: "Border Security Force (BSF Recruitment Portal)",
    agency: "Ministry of Home Affairs",
    category: "defence",
    categoryLabel: "Police & Defence",
    url: "https://rectt.bsf.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official BSF portal for Head Constable (RO/RM), Tradesman, Water Wing, Air Wing, and SI recruitment.",
    tags: ["bsf", "bsf recruitment", "bsf tradesman", "bsf hc ro rm", "capf"],
    popularExam: "BSF Tradesman & Head Constable",
    featured: false,
  },

  // ==========================================
  // POSTAL & RURAL (INDIA POST GDS)
  // ==========================================
  {
    id: "portal-india-post-gds",
    name: "India Post GDS Online Engagement Portal",
    agency: "Department of Posts, Ministry of Communications",
    category: "postal",
    categoryLabel: "Panchayat & Postal",
    url: "https://indiapostgdsonline.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official 10th pass direct recruitment portal for Gramin Dak Sevak (GDS), Branch Postmaster (BPM), and Assistant Branch Postmaster (ABPM).",
    tags: ["india post", "gds", "gramin dak sevak", "post office job", "10th pass job", "postman"],
    popularExam: "India Post GDS (Gramin Dak Sevak)",
    featured: true,
  },
  {
    id: "portal-department-of-posts",
    name: "Department of Posts Official Portal",
    agency: "Ministry of Communications",
    category: "postal",
    categoryLabel: "Panchayat & Postal",
    url: "https://www.indiapost.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Main postal department site for Staff Car Driver, Postal Assistant, Sorting Assistant, and sports quota notifications.",
    tags: ["india post official", "post assistant", "sorting assistant", "post office"],
    popularExam: "Postal Assistant & Staff Driver",
    featured: false,
  },

  // ==========================================
  // TEACHING & EDUCATION (CTET, KVS, NVS)
  // ==========================================
  {
    id: "portal-ctet",
    name: "Central Teacher Eligibility Test (CTET Official)",
    agency: "Central Board of Secondary Education (CBSE)",
    category: "teaching",
    categoryLabel: "Teaching & Education",
    url: "https://ctet.nic.in/",
    stateOrRegion: "All India (Central)",
    description: "Official portal for CTET application, admit card download, response sheet, and eligibility certification.",
    tags: ["ctet", "cbse ctet", "teacher eligibility", "primary teacher", "ctet online"],
    popularExam: "CTET Paper I & Paper II",
    featured: true,
  },
  {
    id: "portal-kvs",
    name: "Kendriya Vidyalaya Sangathan (KVS Official)",
    agency: "Ministry of Education",
    category: "teaching",
    categoryLabel: "Teaching & Education",
    url: "https://kvsangathan.nic.in/",
    stateOrRegion: "All India (Central)",
    description: "Official portal for PRT (Primary Teacher), TGT, PGT, Principal, Vice-Principal, and Non-Teaching recruitment.",
    tags: ["kvs", "kvs prt", "kvs tgt", "kvs pgt", "kendriya vidyalaya", "teaching jobs"],
    popularExam: "KVS PRT / TGT / PGT",
    featured: true,
  },
  {
    id: "portal-nvs",
    name: "Navodaya Vidyalaya Samiti (NVS Official)",
    agency: "Ministry of Education",
    category: "teaching",
    categoryLabel: "Teaching & Education",
    url: "https://navodaya.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official recruitment portal for Jawahar Navodaya Vidyalaya TGT, PGT, Staff Nurse, and Non-Teaching cadre posts.",
    tags: ["nvs", "navodaya", "nvs tgt", "nvs pgt", "jnv teacher"],
    popularExam: "NVS TGT / PGT / Non-Teaching",
    featured: false,
  },

  // ==========================================
  // PSUS & RESEARCH INSTITUTES (ISRO, DRDO, BARC)
  // ==========================================
  {
    id: "portal-isro",
    name: "ISRO Careers & Recruitment (ICRB Portal)",
    agency: "Indian Space Research Organisation (Dept of Space)",
    category: "psu",
    categoryLabel: "PSU & Engineering",
    url: "https://www.isro.gov.in/Careers.html",
    stateOrRegion: "All India (Central)",
    description: "Official ISRO portal for Scientist/Engineer 'SC', Technical Assistant, Technician 'B', and Apprentice recruitment.",
    tags: ["isro", "isro careers", "scientist sc", "isro recruitment", "space jobs", "engineering"],
    popularExam: "ISRO Scientist / Technical Assistant",
    featured: true,
  },
  {
    id: "portal-drdo",
    name: "DRDO Recruitment & Assessment Centre (RAC)",
    agency: "Defence Research and Development Organisation",
    category: "psu",
    categoryLabel: "PSU & Engineering",
    url: "https://rac.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official DRDO portal for Scientist 'B' via GATE, CEPTAM (Senior Technical Assistant & Technician), and JRF fellows.",
    tags: ["drdo", "drdo rac", "ceptam", "drdo scientist", "defence research"],
    popularExam: "DRDO CEPTAM & Scientist 'B'",
    featured: true,
  },
  {
    id: "portal-barc",
    name: "Bhabha Atomic Research Centre (BARC Recruitment)",
    agency: "Department of Atomic Energy",
    category: "psu",
    categoryLabel: "PSU & Engineering",
    url: "https://barc.gov.in/careers/",
    stateOrRegion: "All India (Central)",
    description: "Official BARC recruitment portal for Scientific Officer, Stipendary Trainee Category I & II, and Technical Officer.",
    tags: ["barc", "atomic energy", "stipendiary trainee", "scientific officer", "barc recruitment"],
    popularExam: "BARC Stipendiary Trainee & OCES",
    featured: false,
  },
  {
    id: "portal-ongc",
    name: "ONGC Careers Portal",
    agency: "Oil and Natural Gas Corporation",
    category: "psu",
    categoryLabel: "PSU & Engineering",
    url: "https://ongcindia.com/web/eng/career",
    stateOrRegion: "All India (Central)",
    description: "Official ONGC career portal for Graduate Trainees via GATE, Medical Officers, Executive, and Apprentice posts.",
    tags: ["ongc", "ongc gate", "psu job", "oil corporation", "graduate trainee"],
    popularExam: "ONGC Executive via GATE",
    featured: false,
  },

  // ==========================================
  // STATE PUBLIC SERVICE COMMISSIONS (STATE PSCs)
  // ==========================================
  {
    id: "portal-wbpsc",
    name: "West Bengal Public Service Commission (WBPSC)",
    agency: "Government of West Bengal",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://wbpsc.gov.in/",
    stateOrRegion: "West Bengal",
    description: "Official WBPSC portal for WBCS (Exe), WB Judicial Service, Miscellaneous Services, and Food SI recruitment.",
    tags: ["wbpsc", "wbcs", "west bengal psc", "food si", "wb psc online", "kolkata job"],
    popularExam: "WBCS Executive / Food SI",
    featured: true,
  },
  {
    id: "portal-wbp-constable",
    name: "West Bengal Police Recruitment Board (WBPRB)",
    agency: "West Bengal Police",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://prb.wb.gov.in/",
    stateOrRegion: "West Bengal",
    description: "Official portal for WB Police Constable, Lady Constable, SI, Wireless Operator, and Excise Constable recruitment.",
    tags: ["wbprb", "wb police", "kolkata police", "wb constable", "lady constable"],
    popularExam: "WB Police Constable / SI",
    featured: true,
  },
  {
    id: "portal-uppsc",
    name: "Uttar Pradesh Public Service Commission (UPPSC)",
    agency: "Government of Uttar Pradesh",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://uppsc.up.nic.in/",
    stateOrRegion: "Uttar Pradesh",
    description: "Official UPPSC portal for UPPCS Combined State/Upper Subordinate, RO/ARO, Staff Nurse, and Lecturer exams.",
    tags: ["uppsc", "uppcs", "up pcs", "ro aro", "up govt jobs"],
    popularExam: "UPPCS Executive / RO ARO",
    featured: true,
  },
  {
    id: "portal-upsssc",
    name: "Uttar Pradesh Subordinate Services Selection Commission (UPSSSC)",
    agency: "Government of Uttar Pradesh",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://upsssc.gov.in/",
    stateOrRegion: "Uttar Pradesh",
    description: "Official UPSSSC portal for UP PET (Preliminary Eligibility Test), Lekhpal, VDO (Gram Vikas Adhikari), and Junior Assistant.",
    tags: ["upssssc", "up pet", "lekhpal", "vdo", "up subordinate"],
    popularExam: "UP PET / Lekhpal / VDO",
    featured: true,
  },
  {
    id: "portal-bpsc",
    name: "Bihar Public Service Commission (BPSC)",
    agency: "Government of Bihar",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://bpsc.bih.nic.in/",
    stateOrRegion: "Bihar",
    description: "Official BPSC portal for Combined Competitive Exam (CCE), BPSC TRE Teacher Recruitment, and Assistant Engineer.",
    tags: ["bpsc", "bihar psc", "bpsc tre", "bpsc cce", "bihar teacher"],
    popularExam: "BPSC CCE / BPSC TRE Teacher",
    featured: true,
  },
  {
    id: "portal-bssc",
    name: "Bihar Staff Selection Commission (BSSC)",
    agency: "Government of Bihar",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://bssc.bihar.gov.in/",
    stateOrRegion: "Bihar",
    description: "Official BSSC portal for Inter Level CGL, Graduate Level CGL, Office Attendant, and Panchayat Secretary jobs.",
    tags: ["bssc", "bssc inter level", "bssc cgl", "bihar ssc"],
    popularExam: "BSSC Inter Level & Graduate CGL",
    featured: true,
  },
  {
    id: "portal-mpsc",
    name: "Maharashtra Public Service Commission (MPSC)",
    agency: "Government of Maharashtra",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://mpsc.gov.in/",
    stateOrRegion: "Maharashtra",
    description: "Official MPSC portal for State Services Exam (Rajyaseva), Subordinate Services (PSI/STI/ASO), and Engineering Services.",
    tags: ["mpsc", "rajyaseva", "mpsc psi", "maharashtra psc", "mpsc online"],
    popularExam: "MPSC Rajyaseva / PSI STI ASO",
    featured: false,
  },
  {
    id: "portal-tnpsc",
    name: "Tamil Nadu Public Service Commission (TNPSC)",
    agency: "Government of Tamil Nadu",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://www.tnpsc.gov.in/",
    stateOrRegion: "Tamil Nadu",
    description: "Official TNPSC portal for Group 1, Group 2/2A, Group 4 (VAO), and Combined Engineering Services.",
    tags: ["tnpsc", "tnpsc group 4", "tnpsc group 2", "vao", "tamil nadu psc"],
    popularExam: "TNPSC Group 4 / Group 2",
    featured: false,
  },
  {
    id: "portal-mppsc",
    name: "Madhya Pradesh Public Service Commission (MPPSC)",
    agency: "Government of Madhya Pradesh",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://mppsc.mp.gov.in/",
    stateOrRegion: "Madhya Pradesh",
    description: "Official MPPSC portal for MP State Service Exam, State Forest Service, Medical Officer, and Assistant Professor.",
    tags: ["mppsc", "mp pcs", "madhya pradesh psc", "mp forest service"],
    popularExam: "MPPSC State Service Exam",
    featured: false,
  },
  {
    id: "portal-rpsc",
    name: "Rajasthan Public Service Commission (RPSC)",
    agency: "Government of Rajasthan",
    category: "state_psc",
    categoryLabel: "State PSC & Subordinate",
    url: "https://rpsc.rajasthan.gov.in/",
    stateOrRegion: "Rajasthan",
    description: "Official RPSC portal for RAS/RTS Combined Competitive Exam, Senior Teacher Grade II, School Lecturer, and Sub-Inspector.",
    tags: ["rpsc", "ras exam", "rajasthan psc", "rpsc teacher", "rpsc si"],
    popularExam: "RPSC RAS / School Lecturer",
    featured: false,
  },

  // ==========================================
  // NATIONAL EMPLOYMENT & APPRENTICESHIP
  // ==========================================
  {
    id: "portal-ncs",
    name: "National Career Service (NCS Portal)",
    agency: "Ministry of Labour & Employment",
    category: "employment",
    categoryLabel: "National Career Hub",
    url: "https://www.ncs.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Government of India's flagship portal connecting jobseekers, government job fairs, skill providers, and counselors.",
    tags: ["ncs", "national career service", "govt job fair", "ncs registration", "labour ministry"],
    popularExam: "Govt Job Fairs & Career Cards",
    featured: true,
  },
  {
    id: "portal-apprenticeship",
    name: "Apprenticeship India Official Portal (NAPS)",
    agency: "Ministry of Skill Development and Entrepreneurship",
    category: "employment",
    categoryLabel: "National Career Hub",
    url: "https://www.apprenticeshipindia.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official National Apprenticeship Promotion Scheme (NAPS) portal for ITI, 10th/12th, and diploma trade apprenticeships.",
    tags: ["naps", "apprenticeship india", "iti apprentice", "trade apprentice", "naps portal"],
    popularExam: "NAPS Trade Apprenticeship",
    featured: true,
  },
  {
    id: "portal-nats",
    name: "National Apprenticeship Training Scheme (NATS)",
    agency: "Ministry of Education (Board of Practical Training)",
    category: "employment",
    categoryLabel: "National Career Hub",
    url: "https://nats.education.gov.in/",
    stateOrRegion: "All India (Central)",
    description: "Official portal for B.E / B.Tech / Diploma / General Graduate apprenticeships in central PSUs & govt departments.",
    tags: ["nats", "graduate apprentice", "diploma apprentice", "education ministry apprentice"],
    popularExam: "NATS Graduate & Diploma Apprentice",
    featured: false,
  },
];
